"""add webhook and schedule models

Revision ID: 4009bb78e750
Revises: b1f4c9a7d2e1
Create Date: 2026-03-22 19:36:44.990529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4009bb78e750'
down_revision = 'b1f4c9a7d2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='任务名称'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment='Cron 表达式'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标类型: api_collection, web_collection, perf_scenario'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('notify_webhook', sa.String(length=500), nullable=True, comment='通知 Webhook (如钉钉/飞书)'),
    sa.Column('notify_events', sa.String(length=50), nullable=True, comment='通知事件: all, failed, passed'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='触发器名称'),
    sa.Column('token', sa.String(length=100), nullable=False, comment='唯一触发Token'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标类型: api_collection, web_collection, perf_scenario'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_tokens')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
