"""补齐缺失的数据库表"""
from alembic import op
import sqlalchemy as sa

revision = '004_add_missing_tables'
down_revision = '003_add_project_pin'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('billing_plans',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(50), unique=True, nullable=False),
        sa.Column('display_name', sa.String(100), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('price_monthly', sa.Float(), server_default='0'),
        sa.Column('price_yearly', sa.Float(), server_default='0'),
        sa.Column('currency', sa.String(10), server_default='CNY'),
        sa.Column('max_projects', sa.Integer(), server_default='5'),
        sa.Column('max_test_cases', sa.Integer(), server_default='100'),
        sa.Column('max_parallel_executions', sa.Integer(), server_default='1'),
        sa.Column('max_ai_calls_monthly', sa.Integer(), server_default='100'),
        sa.Column('max_members', sa.Integer(), server_default='5'),
        sa.Column('max_storage_mb', sa.Integer(), server_default='1024'),
        sa.Column('features', sa.JSON()),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('sort_order', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('organization_id', sa.Integer(), sa.ForeignKey('organizations.id'), nullable=False),
        sa.Column('plan_id', sa.Integer(), sa.ForeignKey('billing_plans.id'), nullable=False),
        sa.Column('status', sa.String(20), server_default='active'),
        sa.Column('billing_cycle', sa.String(10), server_default='monthly'),
        sa.Column('started_at', sa.DateTime()),
        sa.Column('current_period_start', sa.DateTime()),
        sa.Column('current_period_end', sa.DateTime()),
        sa.Column('cancelled_at', sa.DateTime()),
        sa.Column('payment_method', sa.String(50)),
        sa.Column('external_subscription_id', sa.String(255)),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
    )
    op.create_table('usage_records',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('organization_id', sa.Integer(), sa.ForeignKey('organizations.id'), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('projects_count', sa.Integer(), server_default='0'),
        sa.Column('test_cases_count', sa.Integer(), server_default='0'),
        sa.Column('ai_calls_count', sa.Integer(), server_default='0'),
        sa.Column('storage_used_mb', sa.Float(), server_default='0'),
        sa.Column('members_count', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
    )
    op.create_table('branding_configs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('organization_id', sa.Integer(), sa.ForeignKey('organizations.id'), nullable=False),
        sa.Column('platform_name', sa.String(100), server_default='FullScopeTest'),
        sa.Column('logo_url', sa.String(500)),
        sa.Column('favicon_url', sa.String(500)),
        sa.Column('primary_color', sa.String(20), server_default='#2D6A64'),
        sa.Column('footer_text', sa.String(500)),
        sa.Column('custom_css', sa.Text()),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
    )
    op.create_table('dashboard_widgets',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('organization_id', sa.Integer(), sa.ForeignKey('organizations.id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('widget_type', sa.String(50), nullable=False),
        sa.Column('title', sa.String(200)),
        sa.Column('config', sa.JSON()),
        sa.Column('position_x', sa.Integer(), server_default='0'),
        sa.Column('position_y', sa.Integer(), server_default='0'),
        sa.Column('width', sa.Integer(), server_default='6'),
        sa.Column('height', sa.Integer(), server_default='4'),
        sa.Column('is_visible', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
    )
    op.create_table('embedding_cache',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('content_hash', sa.String(64), unique=True, nullable=False),
        sa.Column('embedding', sa.JSON(), nullable=False),
        sa.Column('model', sa.String(100)),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_table('mock_servers',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('project_id', sa.Integer(), sa.ForeignKey('projects.id'), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('base_path', sa.String(500), server_default='/'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_at', sa.DateTime()),
    )
    op.create_table('mock_rules',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('server_id', sa.Integer(), sa.ForeignKey('mock_servers.id'), nullable=False),
        sa.Column('method', sa.String(10), server_default='GET'),
        sa.Column('path', sa.String(500), nullable=False),
        sa.Column('status_code', sa.Integer(), server_default='200'),
        sa.Column('response_body', sa.Text()),
        sa.Column('response_headers', sa.JSON()),
        sa.Column('delay_ms', sa.Integer(), server_default='0'),
        sa.Column('priority', sa.Integer(), server_default='0'),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_table('mock_request_logs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('server_id', sa.Integer(), sa.ForeignKey('mock_servers.id'), nullable=False),
        sa.Column('rule_id', sa.Integer(), sa.ForeignKey('mock_rules.id')),
        sa.Column('method', sa.String(10)),
        sa.Column('path', sa.String(500)),
        sa.Column('headers', sa.JSON()),
        sa.Column('body', sa.Text()),
        sa.Column('response_status', sa.Integer()),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_table('perf_baselines',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('scenario_id', sa.Integer(), sa.ForeignKey('perf_test_scenarios.id'), nullable=False),
        sa.Column('test_result_id', sa.Integer(), sa.ForeignKey('performance_test_results.id')),
        sa.Column('avg_response_time', sa.Float()),
        sa.Column('p95_response_time', sa.Float()),
        sa.Column('p99_response_time', sa.Float()),
        sa.Column('throughput', sa.Float()),
        sa.Column('error_rate', sa.Float()),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime()),
    )
    op.create_table('response_histories',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('case_id', sa.Integer(), sa.ForeignKey('api_test_cases.id')),
        sa.Column('url', sa.String(2000), nullable=False),
        sa.Column('method', sa.String(10)),
        sa.Column('status_code', sa.Integer()),
        sa.Column('response_time_ms', sa.Float()),
        sa.Column('response_size', sa.Integer()),
        sa.Column('created_at', sa.DateTime()),
    )


def downgrade():
    for t in ['response_histories', 'perf_baselines', 'mock_request_logs', 'mock_rules', 'mock_servers', 'embedding_cache', 'dashboard_widgets', 'branding_configs', 'usage_records', 'subscriptions', 'billing_plans']:
        op.drop_table(t)
