"""add performance alert models

Revision ID: a1b2c3d4e5f6
Revises: 4009bb78e750
Create Date: 2026-05-30 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '4009bb78e750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='告警规则名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则描述'),
    sa.Column('scenario_id', sa.Integer(), nullable=True, comment='关联的场景 ID，为空则全局生效'),
    sa.Column('condition_type', sa.String(length=20), server_default='absolute', nullable=False, comment='条件类型: absolute/relative'),
    sa.Column('metric_name', sa.String(length=50), nullable=True, comment='指标名称'),
    sa.Column('operator', sa.String(length=10), nullable=True, comment='比较运算符'),
    sa.Column('threshold_value', sa.Float(), nullable=True, comment='阈值'),
    sa.Column('relative_metric', sa.String(length=50), nullable=True, comment='相对劣化的指标名称'),
    sa.Column('degradation_percentage', sa.Float(), nullable=True, comment='劣化百分比阈值'),
    sa.Column('notify_webhook', sa.String(length=500), nullable=True, comment='Webhook URL'),
    sa.Column('notify_users', sa.JSON(), nullable=True, comment='通知用户 ID 列表'),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['scenario_id'], ['perf_test_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_alert_rules_scenario_id', 'performance_alert_rules', ['scenario_id'], unique=False)
    op.create_index('idx_perf_alert_rules_enabled', 'performance_alert_rules', ['is_enabled'], unique=False)
    op.create_table('performance_alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False, comment='关联的告警规则 ID'),
    sa.Column('test_result_id', sa.Integer(), nullable=True, comment='关联的测试结果 ID'),
    sa.Column('metric_name', sa.String(length=50), nullable=False, comment='触发告警的指标名称'),
    sa.Column('current_value', sa.Float(), nullable=True, comment='当前值'),
    sa.Column('threshold_value', sa.Float(), nullable=True, comment='阈值'),
    sa.Column('message', sa.Text(), nullable=False, comment='告警消息'),
    sa.Column('severity', sa.String(length=20), server_default='warning', nullable=True, comment='严重程度: info/warning/critical'),
    sa.Column('notification_sent', sa.Boolean(), server_default='0', nullable=True, comment='是否已发送通知'),
    sa.Column('notification_error', sa.Text(), nullable=True, comment='通知发送失败的错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['rule_id'], ['performance_alert_rules.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['performance_test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perf_alert_logs_rule_id', 'performance_alert_logs', ['rule_id'], unique=False)
    op.create_index('idx_perf_alert_logs_test_result_id', 'performance_alert_logs', ['test_result_id'], unique=False)
    op.create_index('idx_perf_alert_logs_created_at', 'performance_alert_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_perf_alert_logs_created_at', table_name='performance_alert_logs')
    op.drop_index('idx_perf_alert_logs_test_result_id', table_name='performance_alert_logs')
    op.drop_index('idx_perf_alert_logs_rule_id', table_name='performance_alert_logs')
    op.drop_table('performance_alert_logs')
    op.drop_index('idx_perf_alert_rules_enabled', table_name='performance_alert_rules')
    op.drop_index('idx_perf_alert_rules_scenario_id', table_name='performance_alert_rules')
    op.drop_table('performance_alert_rules')
    # ### end Alembic commands ###
