"""add visual regression models

Revision ID: a1b2c3d4e5f6
Revises: 4009bb78e750
Create Date: 2026-03-22 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '4009bb78e750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='关联的测试用例 ID（api/web/app 测试）'),
    sa.Column('test_type', sa.String(length=20), nullable=False, comment='测试类型: api/web/app'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目 ID'),
    sa.Column('step_index', sa.Integer(), nullable=False, comment='测试步骤索引'),
    sa.Column('step_name', sa.String(length=255), nullable=True, comment='测试步骤名称'),
    sa.Column('baseline_image_path', sa.String(length=500), nullable=False, comment='基准截图存储路径'),
    sa.Column('viewport_width', sa.Integer(), nullable=True, comment='视口宽度'),
    sa.Column('viewport_height', sa.Integer(), nullable=True, comment='视口高度'),
    sa.Column('device_pixel_ratio', sa.Float(), nullable=True, comment='设备像素比'),
    sa.Column('full_page', sa.Boolean(), nullable=True, comment='是否全页截图'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/deprecated/pending'),
    sa.Column('version', sa.Integer(), nullable=True, comment='基准版本号'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='批准人用户 ID'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='批准时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visual_baselines_project_id', 'visual_baselines', ['project_id'], unique=False)
    op.create_index('idx_visual_baselines_step_index', 'visual_baselines', ['step_index'], unique=False)
    op.create_index('idx_visual_baselines_test_case_id', 'visual_baselines', ['test_case_id'], unique=False)
    op.create_table('visual_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=False, comment='关联的测试执行记录 ID'),
    sa.Column('baseline_id', sa.Integer(), nullable=True, comment='关联的基准截图 ID'),
    sa.Column('test_case_id', sa.Integer(), nullable=False, comment='关联的测试用例 ID'),
    sa.Column('test_type', sa.String(length=20), nullable=False, comment='测试类型: api/web/app'),
    sa.Column('step_index', sa.Integer(), nullable=False, comment='测试步骤索引'),
    sa.Column('step_name', sa.String(length=255), nullable=True, comment='测试步骤名称'),
    sa.Column('current_image_path', sa.String(length=500), nullable=False, comment='当前截图存储路径'),
    sa.Column('diff_image_path', sa.String(length=500), nullable=True, comment='差异标注图存储路径'),
    sa.Column('diff_percentage', sa.Float(), nullable=False, comment='差异百分比 (0-100)'),
    sa.Column('diff_pixel_count', sa.Integer(), nullable=True, comment='差异像素数量'),
    sa.Column('total_pixel_count', sa.Integer(), nullable=True, comment='总像素数量'),
    sa.Column('similarity_score', sa.Float(), nullable=True, comment='感知哈希相似度 (0-1)'),
    sa.Column('viewport_width', sa.Integer(), nullable=True, comment='视口宽度'),
    sa.Column('viewport_height', sa.Integer(), nullable=True, comment='视口高度'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='差异阈值 (%)，超过则判定为视觉失败'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/visual_pass/visual_fail/approved/rejected'),
    sa.Column('is_baseline_current', sa.Boolean(), nullable=True, comment='基准截图是否为最新版本'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核人用户 ID'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['baseline_id'], ['visual_baselines.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visual_diffs_baseline_id', 'visual_diffs', ['baseline_id'], unique=False)
    op.create_index('idx_visual_diffs_status', 'visual_diffs', ['status'], unique=False)
    op.create_index('idx_visual_diffs_test_case_id', 'visual_diffs', ['test_case_id'], unique=False)
    op.create_index('idx_visual_diffs_test_run_id', 'visual_diffs', ['test_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visual_diffs_test_run_id', table_name='visual_diffs')
    op.drop_index('idx_visual_diffs_test_case_id', table_name='visual_diffs')
    op.drop_index('idx_visual_diffs_status', table_name='visual_diffs')
    op.drop_index('idx_visual_diffs_baseline_id', table_name='visual_diffs')
    op.drop_table('visual_diffs')
    op.drop_index('idx_visual_baselines_test_case_id', table_name='visual_baselines')
    op.drop_index('idx_visual_baselines_step_index', table_name='visual_baselines')
    op.drop_index('idx_visual_baselines_project_id', table_name='visual_baselines')
    op.drop_table('visual_baselines')
    # ### end Alembic commands ###
