"""add_app_test_models

Revision ID: c1b7c29e3127
Revises: 4009bb78e750
Create Date: 2026-03-22 21:01:55.483654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1b7c29e3127'
down_revision = '4009bb78e750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_test_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_test_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.Text(), nullable=False, comment='Appium Python 测试代码'),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True, comment='android/ios'),
    sa.Column('device_name', sa.String(length=100), nullable=True, comment='设备名称, 如 emulator-5554'),
    sa.Column('app_package', sa.String(length=100), nullable=True, comment='Android: appPackage'),
    sa.Column('app_activity', sa.String(length=100), nullable=True, comment='Android: appActivity'),
    sa.Column('bundle_id', sa.String(length=100), nullable=True, comment='iOS: bundleId'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['app_test_collections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_test_cases', schema=None) as batch_op:
        batch_op.alter_column('last_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='最后执行结果',
               existing_nullable=True)
        batch_op.alter_column('mock_enabled',
               existing_type=sa.BOOLEAN(),
               comment='是否启用 Mock',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('mock_response_code',
               existing_type=sa.INTEGER(),
               comment='Mock 响应状态码',
               existing_nullable=True,
               existing_server_default=sa.text('200'))
        batch_op.alter_column('mock_response_body',
               existing_type=sa.TEXT(),
               comment='Mock 响应体 (通常是 JSON 字符串)',
               existing_nullable=True)
        batch_op.alter_column('mock_response_headers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Mock 响应头',
               existing_nullable=True)
        batch_op.alter_column('mock_delay_ms',
               existing_type=sa.INTEGER(),
               comment='Mock 响应延迟(毫秒)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               comment='关联报告ID',
               existing_comment='鍏宠仈鎶ュ憡ID',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_runs', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               comment='鍏宠仈鎶ュ憡ID',
               existing_comment='关联报告ID',
               existing_nullable=True)

    with op.batch_alter_table('api_test_cases', schema=None) as batch_op:
        batch_op.alter_column('mock_delay_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Mock 响应延迟(毫秒)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('mock_response_headers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Mock 响应头',
               existing_nullable=True)
        batch_op.alter_column('mock_response_body',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Mock 响应体 (通常是 JSON 字符串)',
               existing_nullable=True)
        batch_op.alter_column('mock_response_code',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Mock 响应状态码',
               existing_nullable=True,
               existing_server_default=sa.text('200'))
        batch_op.alter_column('mock_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用 Mock',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('last_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='最后执行结果',
               existing_nullable=True)

    op.drop_table('app_test_scripts')
    op.drop_table('app_test_collections')
    # ### end Alembic commands ###
